### ISSUE TITLE
建议加个遍历

### ISSUE THREAD

**Issue by Hehanzzz** [youki992/CodeStringSearcher#1]
没有遍历，在反编译大型项目cs导出的时候会生成很多文件夹，一个个设置为扫描太过麻烦

**Comment by youki992** [comment]
> 没有遍历，在反编译大型项目cs导出的时候会生成很多文件夹，一个个设置为扫描太过麻烦

建议收到啦师傅，这边考虑更新下

**Comment by youki992** [comment]
已更新
